---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator
policyDefaults:
  namespace: policies
  remediationAction: enforce
  pruneObjectBehavior: DeleteIfCreated
  policySets:
    - acm-feature-placements

placementBindingDefaults:
  name: "acm-feature-placement-binding"

policies:
  - name: generate-feature-placements
    manifests:
      - path: feature-flag-placements.yml
        name: ft-flag-placement

policySets:
  - name: acm-feature-placements
    placement:
      placementName: "clusterset-hub-openshift"
