---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-gitops
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - gitops-operator

placementBindingDefaults:
  name: "gitops-binding"

policies:
  - name: gitops-110-migration
    remediationAction: inform
    manifests:
      - path: migrate-gitops-1.10.yml

  - name: gitops-operator
    dependencies:
      - name: "gitops-110-migration"
        compliance: "Compliant"
    manifests:
      - path: operator-ns.yml
        name: operator-namespace

      - path: argocd-ns.yml
        name: argo-namespace

      - path: operatorpolicy.yml

  - name: gitops-instances
    consolidateManifests: true
    dependencies:
      - name: "gitops-operator"
        compliance: "Compliant"
    manifests:
      - path: argocd-instances/default
        name: argo-instances

      - path: argocd-instances/dev
        name: argo-instances

      - path: argocd-instances/argo-server-host.yml
        name: argocd-instance-host

  - name: gitops-acm-policygenerator
    dependencies:
      - name: "gitops-instances"
        compliance: "Compliant"
    policySets:
      - gitops-acm-hub
    manifests:
      - path: argocd-policygenerator.yml
        name: argo-policygenerator

      - path: applicationset-config/managedclustersetbinding.yml
        name: applicationset-clusterbinding

  - name: gitops-instance-status
    remediationAction: inform
    dependencies:
      - name: "gitops-instances"
        compliance: "Compliant"
    manifests:
      - path: health/argocd-status.yml
        name: argocd-instance-status
        remediationAction: InformOnly

policySets:
  - name: gitops-operator
    placement:
      placementName: "clusterset-all-openshift"

  - name: gitops-acm-hub
    placement:
      placementName: "clusterset-hub-openshift"
