---
apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  name: cluster
spec:
  runOnInfra: '{{ hasNodesWithExactRoles "infra" | bool }}'
  tolerations:
    - key: node-role.kubernetes.io/infra
      operator: Exists
