---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-generator-acm
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - acm-operator
placementBindingDefaults:
  name: "acm-operator-binding"

policies:
  - name: acm-operator
    remediationAction: enforce
    manifests:
      - path: operatorpolicy.yml

  - name: acm-multiclusterhub
    remediationAction: enforce
    dependencies:
      - name: acm-operator
        compliance: "Compliant"
    manifests:
      - path: multiclusterhub.yml
        name: acm-operator-multiclusterhub

policySets:
  - name: acm-operator
    placement:
      placementName: "clusterset-hub-openshift"
