---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: klusterlet-infra-policy-generator
policyDefaults:
  namespace: policies
  remediationAction: enforce
  pruneObjectBehavior: DeleteIfCreated
  policySets:
    - acm-klusterlet-infra

placementBindingDefaults:
  name: "acm-klusterlet-infra-binding"

policies:
  - name: klusterlet-selector-tolerations
    remediationAction: enforce
    manifests:
      - path: infra-selector-tolerations.yml
        name: infra-selector-tolerations

      - path: addondeploymentconfig.yml
        name: infra-deploy-config

policySets:
  - name: acm-klusterlet-infra
    placement:
      placementName: "clusterset-hub-openshift"
